### ISSUE TITLE
Practice using issues on Github

### ISSUE THREAD

**Issue by hayleyrbrooks** [sokolhessnerlab/cap#1]
**Problem**
HRB knows how to create issues just not in GitHub. 

**Solution**
HRB is creating this issue in Github as practice.

- [x] does this checklist work?
- [x] can issues be edited?

**Comment by psokolhessner** [comment]
Looks to me like HRB knows how to create issues in GitHub now.

**Comment by hayleyrbrooks** [comment]
Why did you add the "good first issue" label? Is that standard practice? @psokolhessner

**Comment by psokolhessner** [comment]
Doesn't do much functionally here @hayleyrbrooks , but bigger picture & longer term it can help organize issues. Click "Labels" on right hand side to see all the options (there are many; and these are configurable so if we want to change the possible issue labels for a repository, we 100% can). I think of them like 'tags'.

**Comment by psokolhessner** [comment]
Alright, @hayleyrbrooks given that you appear to be comfortable opening issues, worth closing one too. Add a comment to close this thing out.

**Comment by hayleyrbrooks** [comment]
Issues unlocked! Closing this one out.
